### ISSUE TITLE
NodeJS Get request 

### ISSUE THREAD

**Issue by joqim** [Tabwire/R6Tab-API#23]
I'm a beginner to REST API, I tried writing Get request to fetch player data to this url: https://r6tab.com/api/search.php?platform=uplay&search=Batfcuk.-

using axios, it throws an error, Error: self signed certificate in certificate chain

Do i need an api key to make the request?

**Comment by RAYs3T** [comment]
## What might be your problem
This error means that the certificate could not be validated.

But the site is using an official certificate. So the error might be:
* That you're using a proxy server or Anti-Virus, which is intercepting the SSL traffic and exchanging the certificate.
* Or the client you're using uses an old / invalid certificate store which does not include the Cloudflare certificate.

![image](https://user-images.githubusercontent.com/16596807/67872787-c4311b80-fb32-11e9-9ca0-36a67d5510ec.png)


## Possible solutions
* Check what certificate the site is using when you open it in the browser. -> If it is not the official one, figure out what is changing it (Anti-Virus, Firewall, Child-Filter, ...)
* Check if you can request any other site with your API-Client that is using HTTPs. -> If this is working, it might be the client that does not support this certificate chain. Try to add a certificate to the clients / system certificate store.

Can you share the important portion of the code? Maybe we can figure out what the problem is.

**Comment by DestinyofYeet** [comment]
So i tried to write an get request with the request library in python, but i only get the response 

https://i.imgur.com/3TvEXER.png

This is my code:

https://i.imgur.com/yO0GzJ6.png

Am i doing something wrong, if no, were can i get an api key?
